version: '3.9'
services:
  postgresDb:
    image: postgres:15.6-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgData:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: propostadb
      POSTGRES_USER: postgres
      POSTGRES_DB: "propostadb"
    networks:
      - postgres-network

  pgadmin:
     image: dpage/pgadmin4
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: 'user@mail.com'
       PGADMIN_DEFAULT_PASSWORD: 'user'
     ports:
       - '8083:80'
     depends_on:
       - postgresDb
     networks:
      -  postgres-network

  rabbitmq:
     image: rabbitmq:3-management
     restart: always
     networks:
       - postgres-network
     ports:
       - 5672:15672
     environment:
       RABBITMQ_DEFAULT_USER: guest
       RABBITMQ_DEFAULT_PASS: guest

  backend:
    container_name: msproposta
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_PASSWORD: propostadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/propostadb
      SPRING_RABBITMQ_HOST: localhost
      SPRING_RABBITMQ_PORT: 5672

    depends_on:
      - postgresDb
      - rabbitmq
    networks:
      - postgres-network

volumes:
  pgData:

networks:
  postgres-network:
     driver: bridge