version: '3.9'
services:
  postgresDb:
    image: postgres:15.6-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgData:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: propostadb
      POSTGRES_USER: postgres
      POSTGRES_DB: "propostadb"

    networks:
      - app-network

  pgadmin:
     image: dpage/pgadmin4
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: 'user@mail.com'
       PGADMIN_DEFAULT_PASSWORD: 'user'
     ports:
       - '8083:80'
     depends_on:
       - postgresDb
     networks:
      -  app-network

##  rabbitmq:
##     image: rabbitmq:3-management
##     restart: always
##     networks:
##       - app-network
##     ports:
##       - 5672:5672 #JMS Port

##     environment:
##       RABBITMQ_DEFAULT_USER: guest
##       RABBITMQ_DEFAULT_PASS: guest



volumes:
  pgData:

networks:
  app-network:
     driver: bridge